os: linux
dist: xenial

jobs:
  include:
    - language: go
      go: 1.15.3 tip
      allow_failures:
        - go: tip
      before_script:
        - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
        - go get golang.org/x/lint                        # Linter
        - go get honnef.co/go/tools/cmd/staticcheck       # Badass static analyzer/linter
      script:
        - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
        - go test $(go list ./...)                 # Run all tests
        - go vet ./...                             # go vet is the official Go static analyzer
        - staticcheck $(go list ./...)             # one last linter
      fast_finish: true
    - language: node_js
      node_js: none
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd)/compiler/core:/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make cfimager
        - make test

notifications:
  email: false